version: 2

models:
    - name: bar
      description: "Items dimensional model aggregating data from multiple sources for a unified view of item details."
      config: 
        grants:
          +select: ['{%- if target.name == "dev_re" -%} tester
                  {%- elif target.name == "prod" -%} sys_admin
                  {%- endif -%}'
                  ]
    - name: foo
      description: "Items dimensional model aggregating data from multiple sources for a unified view of item details."
      config: 
        grants:
          +select: ['{%- if target.name == "dev_re" -%} tester
                  {%- elif target.name == "prod" -%} sys_admin
                  {%- endif -%}'
                  ]
    - name: potato
      description: "Items dimensional model aggregating data from multiple sources for a unified view of item details."
      config: 
        grants:
          +select: ['{%- if target.name == "dev_re" -%} tester
                  {%- elif target.name == "prod" -%} sys_admin
                  {%- endif -%}'
                  ]